name: Bryan Dalessandro
favicon: null
layout_spectrum: 0.60903
typography_spectrum: 0.99915
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#232323'
    - '#dae4ed'
    - '#b4c5d0'
    - '#938776'
    - '#000000'
  brandStrength: 0
  lightness: 0.1875
  saturation: 0.375
  rhythmicContrast: 0
purpose: []
