name: Bryan Dalessandro
favicon: null
layout_spectrum: 0.99508728669025
typography_spectrum: 0.43613262264989316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.638330900343135
  lightness: 0.046229385770857334
  saturation: 0.5018915797118098
  rhythmicContrast: 0.851981213549152
purpose: []
