name: Bryan Dalessandro
favicon: null
layout_spectrum: 0.99508728669025
typography_spectrum: 0.43613262264989316
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#ce0e5d'
    - '#52c9d2'
    - '#fda6fa'
  brandStrength: 0.638330900343135
  lightness: 0.046229385770857334
  saturation: 0.5018915797118098
  rhythmicContrast: 0.851981213549152
purpose: []
